services:
  - type: web
    name: setlist-backend
    env: node
    plan: starter
    buildCommand: npm install && npx prisma generate && npx prisma db push
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: "7d"
      - key: PORT
        value: "10000"
    healthCheckPath: /health

  - type: pserv
    name: setlist-database
    env: postgres
    plan: starter
    databaseName: setlist_db
    databaseUser: setlist_user
